// CLI LLM-слоя: вопрос ассистенту, справка по узлу, гипотезы кластеров. Ключ — OPENAI_API_KEY (.env).
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"strconv"
	"time"

	"hackaton/internal/app"
	"hackaton/internal/config"
	"hackaton/internal/services/assistant"
	"hackaton/internal/services/pipeline"

	"go.uber.org/fx"
)

func main() {
	question := flag.String("q", "", "вопрос ассистенту")
	cardGID := flag.String("card", "", "gid для справки по узлу")
	hypotheses := flag.Bool("hypotheses", false, "сгенерировать гипотезы кластеров через LLM и перезаписать выгрузки")
	flag.Parse()

	container := fx.New(
		app.ModuleBase(),
		app.ModuleRepositories(),
		app.ModuleServices(),
		fx.NopLogger,
		fx.Invoke(func(cfg *config.Config, helper assistant.Service, runner pipeline.Service) error {
			ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
			defer cancel()
			fmt.Fprintf(os.Stderr, "llm: enabled=%v model=%s\n", helper.Enabled(), helper.Model())
			switch {
			case *question != "":
				return ask(ctx, helper, *question)
			case *cardGID != "":
				return card(ctx, helper, *cardGID)
			case *hypotheses:
				report, err := runner.Run(ctx, pipeline.RunParams{DataDir: cfg.App.DataDir, OutDir: cfg.App.OutDir, UseLLM: true, WriteOutputs: true})
				if err != nil {
					return err
				}
				fmt.Printf("гипотез из кэша/LLM: %d, выгрузки перезаписаны в %s/\n", report.HypothesesEnriched, cfg.App.OutDir)
				return nil
			default:
				flag.Usage()
				return nil
			}
		}),
	)
	if err := container.Err(); err != nil {
		fmt.Fprintln(os.Stderr, "ошибка:", err)
		os.Exit(1)
	}
}

func ask(ctx context.Context, helper assistant.Service, question string) error {
	answer, err := helper.Ask(ctx, question)
	if err != nil {
		return err
	}
	fmt.Println(answer.Text)
	fmt.Fprintf(os.Stderr, "\ngids: %v, steps: %d, cached: %v\n", answer.GIDs, answer.Steps, answer.Cached)
	return nil
}

func card(ctx context.Context, helper assistant.Service, raw string) error {
	gid, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		return fmt.Errorf("некорректный gid %q", raw)
	}
	result, err := helper.Card(ctx, gid)
	if err != nil {
		return err
	}
	fmt.Println(result.Text)
	fmt.Fprintf(os.Stderr, "\ngenerated by llm: %v\n", result.ByLLM)
	return nil
}
