// CLI для LLM-слоя: вопрос ассистенту, карточка узла, гипотезы кластеров. Ключ — OPENAI_API_KEY (.env).
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"time"

	"hackaton/internal/analysis"
	"hackaton/internal/config"
	"hackaton/internal/data/parquet"
	"hackaton/internal/llm"
	"hackaton/internal/services/assistant"
)

func main() {
	data := flag.String("data", "data", "папка с parquet")
	out := flag.String("out", "out", "папка выгрузок (кэш llm_cache.json)")
	question := flag.String("q", "", "вопрос ассистенту")
	card := flag.String("card", "", "gid для карточки узла")
	hyp := flag.Bool("hypotheses", false, "сгенерировать гипотезы кластеров и переписать clusters.csv")
	flag.Parse()

	cfg, err := config.New()
	if err != nil {
		log.Fatal(err)
	}
	ds, err := parquet.Load(*data)
	if err != nil {
		log.Fatal(err)
	}
	res, err := analysis.Run(ds, analysis.Options{})
	if err != nil {
		log.Fatal(err)
	}
	client := llm.New(llm.Config{APIKey: cfg.LLM.APIKey, Model: cfg.LLM.Model, BaseURL: cfg.LLM.BaseURL})
	cache := llm.OpenCache(*out + "/llm_cache.json")
	svc := assistant.New(res, client, cache)
	fmt.Fprintf(os.Stderr, "llm: enabled=%v model=%s cache=%d\n", client.Enabled(), cfg.LLM.Model, cache.Len())
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	switch {
	case *question != "":
		a, err := svc.Ask(ctx, *question)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(a.Text)
		fmt.Fprintf(os.Stderr, "\ngids: %v, steps: %d, cached: %v\n", a.Gids, a.Steps, a.Cached)
	case *card != "":
		text, gen, err := svc.Card(ctx, *card)
		if err != nil && text == "" {
			log.Fatal(err)
		}
		if err != nil {
			fmt.Fprintf(os.Stderr, "llm недоступен, показан шаблон: %v\n", err)
		}
		fmt.Println(text)
		fmt.Fprintf(os.Stderr, "\ngenerated by llm: %v\n", gen)
	case *hyp:
		n, err := svc.EnrichHypotheses(ctx, 5, 10)
		if err != nil {
			log.Fatal(err)
		}
		if err := analysis.WriteCSV(res, *out); err != nil {
			log.Fatal(err)
		}
		if err := analysis.WriteGraphJSON(res, *out); err != nil {
			log.Fatal(err)
		}
		fmt.Printf("гипотез обновлено: %d, выгрузки перезаписаны в %s/\n", n, *out)
	default:
		flag.Usage()
	}
}
