// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (title)
VALUES ($1)
RETURNING id, title, created_at
`

func (q *Queries) CreateItem(ctx context.Context, db DBTX, title string) (Item, error) {
	row := db.QueryRow(ctx, createItem, title)
	var i Item
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const deleteItem = `-- name: DeleteItem :execrows
DELETE
FROM items
WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, db DBTX, id uuid.UUID) (int64, error) {
	result, err := db.Exec(ctx, deleteItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getItem = `-- name: GetItem :one
SELECT id, title, created_at
FROM items
WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, db DBTX, id uuid.UUID) (Item, error) {
	row := db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, title, created_at
FROM items
ORDER BY created_at DESC
`

func (q *Queries) ListItems(ctx context.Context, db DBTX) ([]Item, error) {
	rows, err := db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
