// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateItem(ctx context.Context, db DBTX, title string) (Item, error)
	DeleteItem(ctx context.Context, db DBTX, id uuid.UUID) (int64, error)
	GetItem(ctx context.Context, db DBTX, id uuid.UUID) (Item, error)
	ListItems(ctx context.Context, db DBTX) ([]Item, error)
}

var _ Querier = (*Queries)(nil)
