// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/assistant": {
            "post": {
                "description": "Ответ строится через инструменты по результату анализа; в gids — упомянутые узлы для подсветки.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assistant"
                ],
                "summary": "Вопрос по графу на естественном языке",
                "operationId": "assistant-ask",
                "parameters": [
                    {
                        "description": "Вопрос",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantdto.AskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantdto.AskResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httperr.Response"
                        }
                    },
                    "503": {
                        "description": "LLM не настроен",
                        "schema": {
                            "$ref": "#/definitions/httperr.Response"
                        }
                    }
                }
            }
        },
        "/assistant/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assistant"
                ],
                "summary": "Доступен ли LLM-ассистент",
                "operationId": "assistant-status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantdto.StatusResponse"
                        }
                    }
                }
            }
        },
        "/clusters": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "Кластеры сети",
                "operationId": "clusters",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/graphdto.ClusterResponse"
                            }
                        }
                    }
                }
            }
        },
        "/graph": {
            "get": {
                "description": "Вся сеть или top-N узлов с соседями; фильтры по роли, кластеру, компоненте.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "Граф переводов",
                "operationId": "graph",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Роль",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Кластер",
                        "name": "cluster",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Компонента",
                        "name": "component",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Топ N и соседи (0 — все)",
                        "name": "top",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/graphdto.SubgraphResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Проверка живости",
                "operationId": "health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.HealthResponse"
                        }
                    }
                }
            }
        },
        "/nodes/{gid}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "Карточка узла и контрагенты",
                "operationId": "node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GID клиента",
                        "name": "gid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/graphdto.NodeCardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperr.Response"
                        }
                    }
                }
            }
        },
        "/nodes/{gid}/card": {
            "get": {
                "description": "Четыре блока: роль и почему, потоки, связи, на что обратить внимание. Без ключа — шаблон (by_llm=false).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assistant"
                ],
                "summary": "Справка по узлу",
                "operationId": "node-card",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GID клиента",
                        "name": "gid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantdto.CardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperr.Response"
                        }
                    }
                }
            }
        },
        "/nodes/{gid}/ego": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "Окружение узла в один или два шага",
                "operationId": "node-ego",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GID клиента",
                        "name": "gid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            1,
                            2
                        ],
                        "type": "integer",
                        "default": 1,
                        "description": "Глубина",
                        "name": "depth",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/graphdto.SubgraphResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperr.Response"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "Поиск по началу GID",
                "operationId": "search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Префикс GID",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Лимит",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/graphdto.NodeDetailResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.Response"
                        }
                    }
                }
            }
        },
        "/top": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "Топ приоритетов",
                "operationId": "top",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 30,
                        "description": "Число узлов",
                        "name": "n",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/graphdto.TopNodeResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "assistantdto.AskRequest": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "question": {
                    "type": "string",
                    "maxLength": 2000
                }
            }
        },
        "assistantdto.AskResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "cached": {
                    "type": "boolean"
                },
                "gids": {
                    "description": "упомянутые gid — для подсветки на графе",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "steps": {
                    "type": "integer"
                }
            }
        },
        "assistantdto.CardResponse": {
            "type": "object",
            "properties": {
                "by_llm": {
                    "description": "false — шаблон (нет ключа или LLM недоступен)",
                    "type": "boolean"
                },
                "gid": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "assistantdto.StatusResponse": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "model": {
                    "type": "string"
                }
            }
        },
        "dto.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "graphdto.ClusterResponse": {
            "type": "object",
            "properties": {
                "component": {
                    "type": "integer"
                },
                "hypothesis": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "n_cycles": {
                    "type": "integer"
                },
                "n_nodes": {
                    "type": "integer"
                },
                "n_seed": {
                    "type": "integer"
                },
                "roles": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "sum_kzt_in": {
                    "type": "number"
                },
                "sum_kzt_internal": {
                    "type": "number"
                },
                "sum_kzt_out": {
                    "type": "number"
                },
                "top_gids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "graphdto.EdgeResponse": {
            "type": "object",
            "properties": {
                "n_tx": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "sum_kzt": {
                    "type": "number"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "graphdto.FeaturesResponse": {
            "type": "object",
            "properties": {
                "active_days": {
                    "type": "integer"
                },
                "authority": {
                    "type": "number"
                },
                "avg_in_tx": {
                    "type": "number"
                },
                "avg_out_tx": {
                    "type": "number"
                },
                "betweenness": {
                    "type": "number"
                },
                "component_id": {
                    "type": "integer"
                },
                "component_size": {
                    "type": "integer"
                },
                "depth": {
                    "type": "integer"
                },
                "fast_forward_share": {
                    "type": "number"
                },
                "hub": {
                    "type": "number"
                },
                "in_cycle": {
                    "type": "boolean"
                },
                "in_deg": {
                    "type": "integer"
                },
                "in_kzt": {
                    "type": "number"
                },
                "in_tx": {
                    "type": "integer"
                },
                "is_seed": {
                    "type": "boolean"
                },
                "max_same_day_payers": {
                    "type": "integer"
                },
                "n_clusters_in": {
                    "type": "integer"
                },
                "n_seed_payers": {
                    "type": "integer"
                },
                "n_seed_upstream": {
                    "type": "integer"
                },
                "out_deg": {
                    "type": "integer"
                },
                "out_kzt": {
                    "type": "number"
                },
                "out_tx": {
                    "type": "integer"
                },
                "pagerank": {
                    "type": "number"
                },
                "pass_through": {
                    "type": "number"
                },
                "reciprocal": {
                    "type": "boolean"
                },
                "repeat_routes": {
                    "type": "integer"
                },
                "truncated": {
                    "type": "boolean"
                },
                "verified_sink": {
                    "type": "boolean"
                }
            }
        },
        "graphdto.NeighborResponse": {
            "type": "object",
            "properties": {
                "gid": {
                    "type": "string"
                },
                "n_tx": {
                    "type": "integer"
                },
                "sum_kzt": {
                    "type": "number"
                }
            }
        },
        "graphdto.NodeCardResponse": {
            "type": "object",
            "properties": {
                "incoming": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graphdto.NeighborResponse"
                    }
                },
                "node": {
                    "$ref": "#/definitions/graphdto.NodeDetailResponse"
                },
                "outgoing": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graphdto.NeighborResponse"
                    }
                }
            }
        },
        "graphdto.NodeDetailResponse": {
            "type": "object",
            "properties": {
                "cluster": {
                    "type": "integer"
                },
                "component": {
                    "type": "integer"
                },
                "depth": {
                    "type": "integer"
                },
                "evidence": {
                    "type": "string"
                },
                "features": {
                    "$ref": "#/definitions/graphdto.FeaturesResponse"
                },
                "id": {
                    "type": "string"
                },
                "in_deg": {
                    "type": "integer"
                },
                "in_kzt": {
                    "type": "number"
                },
                "is_seed": {
                    "type": "boolean"
                },
                "out_deg": {
                    "type": "integer"
                },
                "out_kzt": {
                    "type": "number"
                },
                "priority": {
                    "type": "number"
                },
                "role": {
                    "type": "string"
                },
                "role_score": {
                    "type": "number"
                },
                "truncated": {
                    "type": "boolean"
                }
            }
        },
        "graphdto.NodeResponse": {
            "type": "object",
            "properties": {
                "cluster": {
                    "type": "integer"
                },
                "component": {
                    "type": "integer"
                },
                "depth": {
                    "type": "integer"
                },
                "evidence": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "in_deg": {
                    "type": "integer"
                },
                "in_kzt": {
                    "type": "number"
                },
                "is_seed": {
                    "type": "boolean"
                },
                "out_deg": {
                    "type": "integer"
                },
                "out_kzt": {
                    "type": "number"
                },
                "priority": {
                    "type": "number"
                },
                "role": {
                    "type": "string"
                },
                "role_score": {
                    "type": "number"
                },
                "truncated": {
                    "type": "boolean"
                }
            }
        },
        "graphdto.SubgraphResponse": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graphdto.EdgeResponse"
                    }
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graphdto.NodeResponse"
                    }
                }
            }
        },
        "graphdto.TopNodeResponse": {
            "type": "object",
            "properties": {
                "gid": {
                    "type": "string"
                },
                "priority": {
                    "type": "number"
                },
                "rank": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "why": {
                    "type": "string"
                }
            }
        },
        "httperr.Error": {
            "type": "object",
            "properties": {
                "field": {
                    "description": "поле запроса, если ошибка про него",
                    "type": "string"
                },
                "msg": {
                    "description": "человекочитаемое сообщение",
                    "type": "string",
                    "example": "Не найдено"
                },
                "status": {
                    "description": "машинный код для фронта",
                    "type": "string",
                    "example": "not_found"
                }
            }
        },
        "httperr.Response": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httperr.Error"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Граф денег — API",
	Description:      "Роли, кластеры и приоритеты узлов транзакционной сети (HackAlem AI).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
